### ISSUE TITLE
Design for assignees, labels and time tracking

### ISSUE THREAD

**Issue by yuravenzhik** [Kv065RubySSTeam/projector#6]
@Kerono4ka @Synkevych 
Create db design for following logical entities:

- Assignees
- Labels
- Time tracking

Detailed behavioral description is added in wiki

**Comment by Kerono4ka** [comment]
![labels_assignees_tracking](https://user-images.githubusercontent.com/37984886/80406971-8f2d3800-88cd-11ea-932c-999c7a5acea2.png)
